# Project identification
sonar.projectKey=dev-video-classification

# Source code configuration - multiple sources separated by commas
sonar.sources=src,main.py,Dockerfile
sonar.tests=tests

# Python version specification
sonar.python.version=3.11

# Exclusions
sonar.exclusions=**/migrations/**,**/venv/**,**/__pycache__/**,**/node_modules/**,**/tests/**,**/.pytest_cache/**,**/owasp-reports/**,**/.git/**,**/.github/**

# Test configuration
sonar.python.coverage.reportPaths=coverage.xml
